name: hugo-build

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - web-page/**
      - .github/workflows/hugo-build.yml.yml
  push:
    branches:
      - master
    paths:
      - web-page/**
      - .github/workflows/hugo-build.yml.yml

jobs:
  hugo-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.0

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        working-directory: ./web-page
        run: hugo --gc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-page/public
          force_orphan: true
