name: CI

on:
  push:
    branches: [master]
    paths:
    - 'web-page/**'
    - '.github/**'

jobs:
  build-deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

     - name: Checkout submodules
       shell: bash
       run: |
         auth_header="$(git config --local --get http.https://github.com/.extraheader)"
         git submodule sync --recursive
         git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.3.2
        with:
          hugo-version: '0.60.1'

      - name: Build
        working-directory: ./web-page
        run: hugo --gc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.6.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./web-page/public
        with:
          emptyCommits: false
          forceOrphan: true
